### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by dlotfi** [mkara44/transunet_pytorch#1]
Thanks for your implementation of the TransUNet.
Do you have a link to UFBA_UESC_DENTAL_IMAGES datatset?
I sent a request email about two weeks ago, as stated in their github repo, but haven't received any response from the authors. It seems they don't maintain the dataset anymore.
I'd be really appreciated if it's possible for you to share the dataset.

**Comment by mkara44** [comment]
Hi, could you please share your email address?

**Comment by dlotfi** [comment]
dariush.lotfi@gmail.com
dariush.lotfi@srbiau.ac.ir

Many thanks for your help
