### ISSUE TITLE
Relationship between `out_channels` and other configurations

### ISSUE THREAD

**Issue by lightersss** [mkara44/transunet_pytorch#3]
When I change out_channel to 128, It occurs that `RuntimeError: Given groups=1, weight of size [128, 512, 3, 3], expected input[16, 768, 32, 32] to have 512 channels, but got 768 channels instead`. So, how to change the `out_channels` , should I change other configurations? Thank U so much.

**Comment by LY4C49** [comment]
> When I change out_channel to 128, It occurs that `RuntimeError: Given groups=1, weight of size [128, 512, 3, 3], expected input[16, 768, 32, 32] to have 512 channels, but got 768 channels instead`. So, how to change the `out_channels` , should I change other configurations? Thank U so much.

I think it is because the conv2 module fixes the output channel to 512, in the Encoder of the transunet.py file.
You can try this:
self.conv2 = nn.Conv2d(out_channels * 8, out_channels * 4, kernel_size=3, stride=1, padding=1)
self.norm2 = nn.BatchNorm2d(out_channels * 4)
