### ISSUE TITLE
What is the "model_path"?

### ISSUE THREAD

**Issue by eliesl** [mkara44/transunet_pytorch#5]
Hi, 
Thank you for the repo. What is the "model_path" defined for the training phase? Is it the direction in which the trained model will be saved or is it the direction for a pre-trained model which is used for starting the training? If it is the latter, how we can change the code to train the network from the scratch without the need for a pre-trained model? Any tips will be highly appreciated. 

Thanks,
Elie

**Comment by mkara44** [comment]
Hi,

"model_path" is defined for where model will be saved during training. Model will be trained from the scratch.

Mustafa

**Comment by mouxinyue1** [comment]
Hello, I want to know how to set model_path? I set it to./model and got the following error:
IsADirectoryError: [Errno 21] Is a directory: '/tmp/rv01/mouxinyue/transunet_pytorch/model'

**Comment by mkara44** [comment]
Hi, model_path does not work with just directory path, model name need to be added too.

`--model_path ./model/model.pth`

**Comment by mouxinyue1** [comment]
Thank you very much. This question has been bothering me for a long time


牟新月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mkara44/transunet_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月20日(星期四) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mkara44/transunet_pytorch] What is the "model_path"? (Issue #5)





 
Hi, model_path does not work with just directory path, model name need to be added too.
 
--model_path ./model/model.pth

**Comment by mouxinyue1** [comment]
Hello, I also want to ask whether image_path can use the image of test? What is the image format? I get an error for png images


牟新月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mkara44/transunet_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月20日(星期四) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mkara44/transunet_pytorch] What is the "model_path"? (Issue #5)





 
Hi, model_path does not work with just directory path, model name need to be added too.
 
--model_path ./model/model.pth

**Comment by mkara44** [comment]
Hello, it is implemented for jpg images but you can easily update it by changing `utils/dataset.py` _line 27_ from `.jpg` to `.png`
