### ISSUE TITLE
Does the repo support RGB image and multiple classes segmentation?

### ISSUE THREAD

**Issue by endeavorui** [mkara44/transunet_pytorch#7]
Thanks for sharing your impressive work. I am working on a multi-class semantic segmentation problem with own dataset. I would like to ask if your repo supports the RGB image and multi-class label? What is input data format (image+label_image)? Thank you.

**Comment by mkara44** [comment]
Hi @endeavorui, 

I used OpenCV and it reads image as BGR but I converted them to RGB in DentalDataset class, so it won't be problem for your case. This repo was written for binary semantic segmentation, you should implement your own code for your multi-class problem.

**Comment by endeavorui** [comment]
Thanks very much for the prompt reply. Could you elaborate more on how to formalize the label data for your work? My understanding is that, label image has the same resolution but binary (0,1) values to mask the area. Could you confirm it? Thanks again and wish you the best!

**Comment by mkara44** [comment]
Yes, that's true. Original mask values were 0, 255, I normalized them to 0, 1 in DentalDataset class.

**Comment by endeavorui** [comment]
Thanks @mkara44
