### ISSUE TITLE
Pretrained model and dataset

### ISSUE THREAD

**Issue by sevdeaydogdu** [mkara44/transunet_pytorch#8]
hey, thank you for sharing your great work!! I was just wondering whether did you use any pretrained weights for transunet because orginal transunet paper used it? And dataset issue, you used xray based dataset so why did you open dataset as 3 RGB channel based?

**Comment by mkara44** [comment]
Hi @sevdeaydogdu , thanks for your comment! I didn't use any pretrained weights. You can also use grayscale images as input, the preprocessing step will be faster.
